#!/bin/sh

set_applet()
{
    template_path="/usr/share/meegotouch/applicationextensions/statusindicatormenu-${1}.desktop"
    template_data="[Desktop Entry]\nType=X-MeeGoApplicationExtension\nName=Status Indicator Presence Applet\n\n[X-MeeGoApplicationExtension]\nInterface=com.meego.core.MStatusIndicatorMenuExtensionInterface/1.0\nExtension=libstatusindicatormenu-${2}.so"
    echo -e $template_data > $template_path
}

set +e

if [ "$1" == "configure" ]; then
    set_applet presence avialability
    /sbin/initctl start xsession/sysuid
fi

exit 0
